#!/system/bin/sh

export PATH=/system/bin

path="dev.ukanth.ufirewall"
if [ ! -e /system/bin/iptables ] || [ ! -e /system/bin/ip6tables ]; then #{

startDt="$(head -n 1 /proc/uptime | cut -d . -f 1)"
while :
do
  if [ -d /data/data/com.android.providers.downloads ]
  then
    break
  fi
  sleep 1
done
endDt="$(head -n 1 /proc/uptime | cut -d . -f 1)"

if [ -e /data/data/dev.ukanth.ufirewall/app_bin/iptables ]; then
  path="dev.ukanth.ufirewall"
elif [ -e /data/data/dev.ukanth.ufirewall.donate/app_bin/iptables ]; then
  path="dev.ukanth.ufirewall.donate"
else
  log -p i -t afwall "AFWall does not seem to be installed, waited for $((endDt-startDt)) seconds."
  exit
fi

log -p i -t afwall "Waited $((endDt-startDt)) seconds for /data/data."

fi #}

doit() {
  for i in "$@"
  do
    if [ -x "$i" ]
    then
      "$i" -wP INPUT DROP
      "$i" -wP OUTPUT DROP
      "$i" -wP FORWARD DROP
      return
    fi
  done
}

doit /system/bin/iptables /data/data/$path/app_bin/iptables
doit /system/bin/ip6tables /data/data/$path/app_bin/ip6tables
log -p i -t afwall "IPv4/6 policy set to DROP"